### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by matchstickboy** [LMGsec/Magic-Unicorn-Tool#2]
Hello,

Am attempting to run the Crowdstrike retriever.py script to obtain activites of a test account in our O365 org.  Receiving the following error:

Traceback (most recent call last):
  File "retriever.py", line 96, in <module>
    csv_file = open(args.output, 'w+', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

Encountering the issue on both Windows 10 and Kali using Python 2.7, and on Windows 10 using Python 3.7.  I'm guessing I'm missing a library in Python??  Any help would be appreciated.  Let me know if additional information would help.

Thank you in advance,

Chris

**Comment by nogweii** [comment]
The `encoding=` argument to open() is only valid for Python 3, so make sure you're running with the correct version. If you are executing the file directly, the shebang in retriever.py uses `python`. You can check what version that binary is symlinked to by running `python --version`.

**Comment by Vico311** [comment]
Make sure you do the following as I would think its required:
sudo apt-get upgrade python3
sudo apt-get install python3-pip
pip3 install requests

**Comment by MattDurrin** [comment]
You could try sticking the encoding declaration in the header if you're using python 2.7. I'm working on a version that's compatible with 2.7 currently but it's not quite finished yet.

**Comment by matchstickboy** [comment]
Thank you everybody for your responses.  I tried Vico311's recommendation
first, and it did the trick :-)

Also, thank you Matt for your work in putting this all together.

Cheers all,

Chris

**Comment by MattDurrin** [comment]
My pleasure, Chris. I hope you find it useful. We will be updating and uploading as we go so stay tuned!
