### ISSUE TITLE
Issues with Index range

### ISSUE THREAD

**Issue by Vico311** [LMGsec/Magic-Unicorn-Tool#3]
After generating a valid activities.csv from the Crowdstrike tool I run the MagicUnicorn_v1.py and get
Traceback (most recent call last):
  File "./MagicUnicorn_v1.py", line 57, in <module>
    time_stamp = time_and_date[1]
IndexError: list index out of range

This occurs for every index element with a value greater than zero.

Running python 3.4.3

**Comment by MattDurrin** [comment]
Hmm... the split using the T character should take care of that. I'll run through some tests with 3.4.3 and see if I can reproduce it.

**Comment by MattDurrin** [comment]
So far I've been unable to reproduce this error with python 3.4.3. Can you provide a little more detail about the process that you're using? Here's what I did and it ran without any issues on a test windows 10 vm:
1.) Download and unzip the repo, open admin powershell
2.) cd into the Crowdstrike-Retriever-Scripts directory
3.) run the command c:\Python34\python.exe .\retriever.py --input "account" --output ~\Desktop\activities.csv --token "Auth Token"
4.) cd .. back into the primary directory
5.) run the command c:\Python34\python.exe .\MagicUnicor_v1.py -i ~\Desktop\activities.csv -o ~\Desktop -t test-report


Edit - Just to be sure I created an Ubuntu 16.04 VM and ran the same test with python 3.4.3 through terminal with the same results.
