### ISSUE TITLE
HTTP 401: OAuth token submitted with the request can not be parsed.

### ISSUE THREAD

**Issue by vnc2017** [LMGsec/Magic-Unicorn-Tool#4]
OS - MAC high sierra
Python - 3.6

I have exported OAUTH_TOKEN="Lengthy Token Code" as environment variable

python3 ./retriever.py --output ~/Desktop/activites.csv --user <email> --types MessageDelivered --start 2018-06-01T00:00:00Z

HTTP 401: OAuth token submitted with the request can not be parsed.

Dunno why I am getting the above error. Help would be appreciated.

**Comment by cs-jonathan** [comment]
It appears that you have supplied the tool with an invalid access token. Assuming you are obtaining a token from the OAuth Sandbox, please make sure you copy the _entire value_ from the text box labeled `Access Token`.

**Comment by MattDurrin** [comment]
Have you been able to run the script by pasting the token into the command string instead of using an environment variable?

**Comment by vnc2017** [comment]
Ok here was the problem - On the microsoft dev page while copying the Access Token - I used to double click on the field. It used to terminate copy anywhere it encountered ".". I had to ctrl+a to copy the whole thing. Now it is perfectly working both OUTH_TOKEN environment variable and --token parameter. Thanks cs-jonathan for pointers.

**Comment by MattDurrin** [comment]
Glad you got it sorted vnc2017.
