### ISSUE TITLE
Enjoy this API while it lasts...

### ISSUE THREAD

**Issue by zjt** [LMGsec/Magic-Unicorn-Tool#5]
Heard in conference call today an official Microsoft statement about this Activities API ...

Microsoft has always discouraged the use of undocumented APIs ... The particular outlook API does not guarantee the complete and accurate telemetry data necessary for security investigations ... we are disabling this API in the near future (no ETA)

He also went a bit into the issue of cybersecurity forensics companies selling services based on "secret" access to undocumented APIs and possibly misrepresenting the accuracy of the data.

**Comment by EricZimmerman** [comment]
hi

1) what conference call?
2) who is "he"
3) how was it "official"? is it also online?

**Comment by zjt** [comment]
Not recorded.  It was a sector-specific community call with one of Microsoft's Solution Specialists.  He said that people should reach out to their Microsoft account team to get the statement in writing.
